### ISSUE TITLE
Setup DMG READMEs

### ISSUE THREAD

**Issue by adamwolf** [wayneandlayne/kicad-mac-builder#12]
The DMGs need usage READMEs that are valid for the new system.

**Comment by adamwolf** [comment]
They need to say "You must open KiCad first before opening the standalone apps, or else the standalone apps won't be able to open up due to macOS quarantining."

**Comment by adamwolf** [comment]
You can model from the current READMEs over at https://github.com/wayneandlayne/KiCadMacOSPackaging

**Comment by danngreen** [comment]
README might also want to say something about how to upgrade from an older version when using a case-sensitive drive.
Dragging the "KiCad" folder (uppercase 'C') on the DMG to the Applications folder in order to overwrite a previous folder named "Kicad" (lowercase 'c'), will give an error if the user has a case-insensitive driver (which is the default in OSX).

The OSX error dialog doesn't have a button to allow overwriting the "Kicad" folder with the "KiCad" folder, so the user has to manually remove/rename the old folder.

Screenshot of the error dialog attached:
<img width="401" alt="screen shot 2018-05-21 at 9 55 38 am" src="https://user-images.githubusercontent.com/25355384/40677841-ba6054d8-6333-11e8-8976-158f88839306.png">
